name: Reproducibility Check

on:
  push:
    branches: [ master, main, cross-tissue ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-manuscripts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-docx

    - name: Generate Manuscripts
      run: |
        python generate_manuscripts_docx.py
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Submission_Package
        path: Submission_Package/
